# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yg1HdaXofC-1VxgFdwhiwHZAcuFaVUak
"""

# Unit Converter in Google Colab

def length_converter(value, from_unit, to_unit):
    units = {
        "meter": 1,
        "kilometer": 1000,
        "centimeter": 0.01,
        "millimeter": 0.001,
        "mile": 1609.34,
        "yard": 0.9144,
        "foot": 0.3048,
        "inch": 0.0254
    }
    return value * units[from_unit] / units[to_unit]

def weight_converter(value, from_unit, to_unit):
    units = {
        "kilogram": 1,
        "gram": 0.001,
        "milligram": 0.000001,
        "pound": 0.453592,
        "ounce": 0.0283495
    }
    return value * units[from_unit] / units[to_unit]

def temperature_converter(value, from_unit, to_unit):
    if from_unit == to_unit:
        return value
    if from_unit == "celsius":
        return (value * 9/5 + 32) if to_unit == "fahrenheit" else (value + 273.15)
    if from_unit == "fahrenheit":
        return (value - 32) * 5/9 if to_unit == "celsius" else ((value - 32) * 5/9 + 273.15)
    if from_unit == "kelvin":
        return (value - 273.15) if to_unit == "celsius" else ((value - 273.15) * 9/5 + 32)

def unit_converter():
    print("Choose category: length / weight / temperature")
    category = input("Category: ").lower()

    value = float(input("Enter value: "))
    from_unit = input("From unit: ").lower()
    to_unit = input("To unit: ").lower()

    if category == "length":
        result = length_converter(value, from_unit, to_unit)
    elif category == "weight":
        result = weight_converter(value, from_unit, to_unit)
    elif category == "temperature":
        result = temperature_converter(value, from_unit, to_unit)
    else:
        print("Invalid category")
        return

    print(f"{value} {from_unit} = {result:.4f} {to_unit}")

unit_converter()

