# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wTFop68XVHPuByGrIHFcy-H5UEcOrzgZ
"""

import re

def check_password_strength(password):
    strength = 0
    criteria = {
        'length': len(password) >= 8,
        'lowercase': bool(re.search(r'[a-z]', password)),
        'uppercase': bool(re.search(r'[A-Z]', password)),
        'digit': bool(re.search(r'\d', password)),
        'special': bool(re.search(r'[^A-Za-z0-9]', password)),
    }

    strength = sum(criteria.values())

    if strength == 5:
        return "Very Strong 🔒"
    elif strength == 4:
        return "Strong 💪"
    elif strength == 3:
        return "Medium 🟡"
    elif strength == 2:
        return "Weak ⚠️"
    else:
        return "Very Weak ❌"

# Input from user
password = input("Enter your password: ")
print("Password Strength:", check_password_strength(password))